# -*- coding: utf-8 -*-
"""Remote Work & Mental Health EDA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOpaeVtBWguoGY7_mDH78PIRLA7Y82iQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Set visualization styles
sns.set(style="whitegrid")

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/CC2/Impact_of_Remote_Work_on_Mental_Health.csv')

# Display the first few rows of the dataset
df.head(10)

# Overview of the dataset
df.info()

# Check for missing values
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

# Get statistical summary of numerical columns
df.describe()

# Plotting the age distribution
plt.figure(figsize=(10, 6))
sns.histplot(df['Age'], bins=15, kde=True, color='red')
plt.title('Age Distribution of Employees')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Pie chart for gender distribution
gender_counts = df['Gender'].value_counts()
plt.figure(figsize=(6, 6))
plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%', startangle=90, colors=['skyblue', 'lightgreen'])
plt.title('Gender Distribution')
plt.show()

# Job role distribution
plt.figure(figsize=(12, 6))
sns.countplot(data=df, y='Job_Role', order=df['Job_Role'].value_counts().index, palette='viridis')
plt.title('Job Role Distribution')
plt.xlabel('Count')
plt.ylabel('Job Role')
plt.show()

# Industry distribution
plt.figure(figsize=(12, 6))
sns.countplot(data=df, y='Industry', order=df['Industry'].value_counts().index, palette='magma')
plt.title('Industry Distribution')
plt.xlabel('Count')
plt.ylabel('Industry')
plt.show()

# Boxplot for Years of Experience vs. Satisfaction with Remote Work
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Years_of_Experience', y='Satisfaction_with_Remote_Work', palette='coolwarm')
plt.title('Satisfaction with Remote Work by Years of Experience')
plt.xlabel('Years of Experience')
plt.ylabel('Satisfaction with Remote Work')
plt.show()

# Bar plot for Work Location vs. Productivity Change
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='Work_Location', hue='Productivity_Change', palette='Set2')
plt.title('Work Location vs. Productivity Change')
plt.xlabel('Work Location')
plt.ylabel('Count')
plt.legend(title='Productivity Change')
plt.show()

# Countplot for Work-Life Balance Rating
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='Work_Life_Balance_Rating', palette='pastel')
plt.title('Work-Life Balance Rating')
plt.xlabel('Work-Life Balance Rating')
plt.ylabel('Count')
plt.show()

# Countplot for Mental Health Condition
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='Mental_Health_Condition', palette='Set1')
plt.title('Mental Health Condition of Employees')
plt.xlabel('Mental Health Condition')
plt.ylabel('Count')
plt.show()

# Pie chart for Access to Mental Health Resources
plt.figure(figsize=(8, 8))
df['Access_to_Mental_Health_Resources'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, colors=['lightgreen', 'salmon'])
plt.title('Access to Mental Health Resources')
plt.ylabel('')
plt.show()

# Scatter plot for Number of Virtual Meetings vs. Satisfaction with Remote Work
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Number_of_Virtual_Meetings', y='Satisfaction_with_Remote_Work', hue='Gender', palette='deep')
plt.title('Number of Virtual Meetings vs. Satisfaction with Remote Work')
plt.xlabel('Number of Virtual Meetings')
plt.ylabel('Satisfaction with Remote Work')
plt.show()

# Bar plot for Physical Activity vs. Satisfaction with Remote Work
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='Physical_Activity', hue='Satisfaction_with_Remote_Work', palette='pastel')
plt.title('Physical Activity vs. Satisfaction with Remote Work')
plt.xlabel('Physical Activity')
plt.ylabel('Count')
plt.legend(title='Satisfaction with Remote Work')
plt.show()

# Correlation matrix heatmap with only numeric columns
plt.figure(figsize=(12, 8))
numeric_df = df.select_dtypes(include=[np.number])  # Select only numeric columns
correlation_matrix = numeric_df.corr()

sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm', mask=np.triu(correlation_matrix))
plt.title('Correlation Matrix')
plt.show()

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd

# Sample data
data = {
    'Age': [25, 30, 35, 40, 45],
    'Hours_Worked_Per_Week': [40, 45, 38, 50, 55],
    'Satisfaction_with_Remote_Work': [3, 4, 2, 5, 1]
}

df = pd.DataFrame(data)

# Create a 3D scatter plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(df['Age'], df['Hours_Worked_Per_Week'], df['Satisfaction_with_Remote_Work'], c='b', marker='o')

ax.set_xlabel('Age')
ax.set_ylabel('Hours Worked per Week')
ax.set_zlabel('Satisfaction with Remote Work')

plt.title('3D Scatter Plot')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Check the column names
print("Column Names:")
print(df.columns)

# Check the first few rows of the DataFrame
print("\nDataFrame Head:")
print(df.head())

# Create the count plot based on 'Satisfaction_with_Remote_Work'
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='Satisfaction_with_Remote_Work', palette='viridis')
plt.title('Satisfaction with Remote Work')
plt.xlabel('Satisfaction Level')
plt.ylabel('Count')
plt.show()
